version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3030:3030'
    volumes:
      - /client/node_modules
      - .:/client
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - .:/client
    command: ['npm', 'run', 'test']
